"""Compare two output ZIP files from old vs new Braille workflows.

Usage:
  python scripts/compare_output_zips.py \
    --expected-zip C:\\path\\to\\expected.zip \
    --actual-zip C:\\path\\to\\actual.zip
"""

from __future__ import annotations

import argparse
import tempfile
import zipfile
from dataclasses import dataclass
from pathlib import Path


@dataclass
class CompareResult:
    missing_folders: list[str]
    extra_folders: list[str]
    missing_files: list[str]
    extra_files: list[str]
    changed_xml_files: list[str]
    changed_brf_files: list[str]
    unreadable_pairs: list[str]

    @property
    def identical(self) -> bool:
        return not (
            self.missing_folders
            or self.extra_folders
            or self.missing_files
            or self.extra_files
            or self.changed_xml_files
            or self.changed_brf_files
            or self.unreadable_pairs
        )


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for comparing two output ZIP files."""

    parser = argparse.ArgumentParser(description="Compare expected vs actual output ZIP files.")
    parser.add_argument("--expected-zip", required=True, type=Path, help="Reference ZIP from old workflow")
    parser.add_argument("--actual-zip", required=True, type=Path, help="ZIP generated by new Python pipeline")
    return parser.parse_args()


def _safe_extract_zip(zip_path: Path, destination: Path) -> None:
    """Extract a ZIP while blocking path traversal entries."""

    with zipfile.ZipFile(zip_path, "r") as archive:
        dest_root = destination.resolve()
        for member in archive.infolist():
            member_path = destination / member.filename
            if not str(member_path.resolve()).startswith(str(dest_root)):
                raise ValueError(f"Unsafe ZIP entry detected: {member.filename}")
        archive.extractall(destination)


def _collect_dirs(root: Path) -> set[str]:
    """Return all relative directory paths from an extracted tree."""

    result: set[str] = set()
    for path in root.rglob("*"):
        if path.is_dir():
            rel = path.relative_to(root).as_posix()
            if rel and rel != ".":
                result.add(rel)
    return result


def _collect_files(root: Path) -> set[str]:
    """Return all relative file paths from an extracted tree."""

    return {path.relative_to(root).as_posix() for path in root.rglob("*") if path.is_file()}


def compare_output_zips(expected_zip: Path, actual_zip: Path) -> CompareResult:
    """Compare structure and selected file contents of two output ZIPs.

    Compares:
    - folder structure
    - file names
    - `.xml` content (byte-for-byte)
    - `.brf` content (byte-for-byte)
    """

    with tempfile.TemporaryDirectory(prefix="zip_compare_") as temp_dir:
        temp_root = Path(temp_dir)
        expected_root = temp_root / "expected"
        actual_root = temp_root / "actual"
        expected_root.mkdir(parents=True, exist_ok=True)
        actual_root.mkdir(parents=True, exist_ok=True)

        _safe_extract_zip(expected_zip, expected_root)
        _safe_extract_zip(actual_zip, actual_root)

        expected_dirs = _collect_dirs(expected_root)
        actual_dirs = _collect_dirs(actual_root)
        expected_files = _collect_files(expected_root)
        actual_files = _collect_files(actual_root)

        missing_folders = sorted(expected_dirs - actual_dirs)
        extra_folders = sorted(actual_dirs - expected_dirs)

        missing_files = sorted(expected_files - actual_files)
        extra_files = sorted(actual_files - expected_files)

        common_files = sorted(expected_files & actual_files)
        changed_xml_files: list[str] = []
        changed_brf_files: list[str] = []
        unreadable_pairs: list[str] = []

        for rel in common_files:
            suffix = Path(rel).suffix.lower()
            if suffix not in {".xml", ".brf"}:
                continue

            expected_path = expected_root / rel
            actual_path = actual_root / rel
            try:
                expected_bytes = expected_path.read_bytes()
                actual_bytes = actual_path.read_bytes()
            except Exception:
                unreadable_pairs.append(rel)
                continue

            if expected_bytes != actual_bytes:
                if suffix == ".xml":
                    changed_xml_files.append(rel)
                elif suffix == ".brf":
                    changed_brf_files.append(rel)

        return CompareResult(
            missing_folders=missing_folders,
            extra_folders=extra_folders,
            missing_files=missing_files,
            extra_files=extra_files,
            changed_xml_files=sorted(changed_xml_files),
            changed_brf_files=sorted(changed_brf_files),
            unreadable_pairs=sorted(unreadable_pairs),
        )


def _print_section(title: str, items: list[str]) -> None:
    """Print a human-readable section for manual review."""

    print(f"\n{title} ({len(items)}):")
    if not items:
        print("- geen")
        return
    for item in items:
        print(f"- {item}")


def main() -> int:
    """Run CLI comparison and print a readable summary report."""

    args = parse_args()

    if not args.expected_zip.is_file():
        print(f"ERROR: expected zip niet gevonden: {args.expected_zip}")
        return 2
    if not args.actual_zip.is_file():
        print(f"ERROR: actual zip niet gevonden: {args.actual_zip}")
        return 2

    try:
        result = compare_output_zips(args.expected_zip, args.actual_zip)
    except Exception as exc:
        print(f"ERROR: vergelijking mislukt: {exc}")
        return 2

    print("=== ZIP Vergelijking ===")
    print(f"Expected: {args.expected_zip}")
    print(f"Actual:   {args.actual_zip}")

    _print_section("Ontbrekende folders in actual", result.missing_folders)
    _print_section("Extra folders in actual", result.extra_folders)
    _print_section("Ontbrekende bestanden in actual", result.missing_files)
    _print_section("Extra bestanden in actual", result.extra_files)
    _print_section("XML inhoudsverschillen", result.changed_xml_files)
    _print_section("BRF inhoudsverschillen", result.changed_brf_files)
    _print_section("Niet-leesbare bestandparen", result.unreadable_pairs)

    print("\n=== Samenvatting ===")
    if result.identical:
        print("VOLLEDIG IDENTIEK")
        return 0

    print("NIET IDENTIEK")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
